### ISSUE TITLE
File not closed

### ISSUE THREAD

**Issue by DuzaBF** [MicheleCotrufo/pdf2doi#17]
Hi, 

The function `pdf2doi_singlefile` does not close the opened pdf file. The close file statement is not executed due to return statements on successful identifier finding.

https://github.com/MicheleCotrufo/pdf2doi/blob/d8e71179dc12932c8a01d8e41e29186c4d64a7cb/pdf2doi/main.py#L161-L165

This causes the issue with `pdf-rename` on Windows. The renaming attempt results in access error as file is opened by the script itself.

I'll make PR shortly to fix this.

**Comment by MicheleCotrufo** [comment]
I merged the contribution from DuzaBF, and made some additional changes to the code to make sure that a `result` dictionary with the key 'identifier' is always returned. This should fix this bug. 
Please download the version 1.3 of `pdf2doi` :) I will also add the requirement in the requirements.txt of `pdfrenamer`
