### ISSUE TITLE
Add file DOI check to URL paths

### ISSUE THREAD

**Issue by DJRHails** [MicheleCotrufo/pdf2doi#19]
Often a search can surface DOI descriptors in the URL path alone, for instance:
```
[pdf2doi]: Performing google search with key "The Experimental Generation of Interpersonal Closeness: A Procedure and Some Preliminary Findings"
[pdf2doi]: and looking at the first 6 results...
[pdf2doi]: Looking for a valid identifier in the search result #1 : https://journals.sagepub.com/doi/pdf/10.1177/0146167297234003
[pdf2doi]: Looking for a valid identifier in the search result #2 : https://journals.sagepub.com/doi/abs/10.1177/0146167297234003
```
Supporting this would give quicker identifications, but also allow for occasions, such as this, where the DOI can't be extracted from the actual page.

[https://doi.org/10.1177/0146167297234003](https://doi.org/10.1177%2F0146167297234003)

**Comment by MicheleCotrufo** [comment]
That's an interesting suggestion, thanks! I will implement it in the next version!

**Comment by DJRHails** [comment]
I ended up implementing [this](https://github.com/DJRHails/pdf2doi/commit/5af1462c2822bd7d506e14f8344b279c7d92b263) along with a few other improvements on a [fork](https://github.com/DJRHails/pdf2doi).

Happy to create a PR to merge upstream if there is interest.

**Comment by MicheleCotrufo** [comment]
Thanks a lot for your efforts! 
Yes, can you create the PR? I will check it in detail and approve it within a few days.

**Comment by DJRHails** [comment]
See https://github.com/MicheleCotrufo/pdf2doi/pull/20
