### ISSUE TITLE
All arXiv articles now have DOIs

### ISSUE THREAD

**Issue by newmanrs** [MicheleCotrufo/pdf2doi#21]
Apparently the arXiv [blog](https://blog.arxiv.org/2022/02/17/new-arxiv-articles-are-now-automatically-assigned-dois/) has announced that as of Feb 2022 all arxiv articles have DOIs.

Furthermore the DOI's share a unified prefix and the arXiv IDs as a suffix:  

> "An author can determine their article’s DOI by using the DOI prefix https://doi.org/10.48550/ followed by the arXiv ID (replacing the colon with a period). For example, the arXiv ID [arXiv:2202.01037](https://arxiv.org/abs/2202.01037) will translate to the DOI link https://doi.org/10.48550/arXiv.2202.01037"

Perhaps could be grounds for a 2.0 release that returns DOI for arXiv articles.

**Comment by MicheleCotrufo** [comment]
Thanks for reporting this! Yes, I will definitely look into implementing this, should be an easy addition.

**Comment by MicheleCotrufo** [comment]
Sorry for the late reply. I just released a new version (1.5rc1) which includes this functionality. You can install it via
`pip install pdf2doi==1.5rc1`

Now, whenever possible `pdf2doi` will replace the arXiv ID by a DOI. This can be either the DOI of a journal publication (if the paper has been published in a journal and the authors have added the DOI to the arXiv metadata) or the DOI provided by arXiv. This functionality can be disabled by adding the command `-no_arxiv2doi` to the `pdf2doi` invocation.

Could you please download this last version and do some tests with it? Thanks!
