### ISSUE TITLE
Installation failed due to pymupdf==1.21.0

### ISSUE THREAD

**Issue by MiuKaShi** [MicheleCotrufo/pdf2doi#28]
Hi, I am an arch linux user.
Installing pdf2doi via pipx always failed.
After checking, I found that due to pymupdf==1.21.0, and change to the latest version of pymupdf. 
everything works well.
So I recommended to update the version of the pymudf dependencies.

**Comment by MicheleCotrufo** [comment]
Thanks! I'll add it to the to-do list for next release!

**Comment by sga-13** [comment]
I was able to install it by downloading `pdf2doi` source, and I just edited out the ==`1.21.0` (I dont know if there were any other name space or breaking changes, I just wanted to try) and it works, I tried to check many papers, and it seems to be fine (I installed almost all dependencies through paru (so main/extra repos or aur)

**Comment by MicheleCotrufo** [comment]
This should be fixed with version 1.7 (just published), please re-open the issue if the problem persists.
