### ISSUE TITLE
Conflict with requirements

### ISSUE THREAD

**Issue by AlessandroCotrufo** [MicheleCotrufo/pdf2doi#32]
On Windows 11, using python 3.12.2, if I try to pip install pdf2doi I eventually get the following error

Failed to build pymupdf
ERROR: Could not build wheels for pymupdf, which is required to install pyproject.toml-based projects

My hypotesis is that the specific version of pymupdf specified in the requirements (pymupdf==1.21.0) does not have a release for latest python version. I tried relaxing that requirement and it seems like the tool is installed and works normally. Was there a reason for that specific version?

**Comment by MicheleCotrufo** [comment]
Seems the same issue as here https://github.com/MicheleCotrufo/pdf2doi/issues/28 
Not sure why I set `pymupdf==1.21.0` instead of `pymupdf>=1.21.0` in one of the last commits. Might have been a mistake. Will revert it to `pymupdf>=1.21.0`.

**Comment by gzurowski** [comment]
@MicheleCotrufo Will you release a new version of pdf2doi with requirements set to `pymupdf>=1.21.0`?

**Comment by MicheleCotrufo** [comment]
@gzurowski I just released version 1.7rc1 with this change. Can you test it on your end? Probably better test it in a dedicated empty environment.
I did some test, and the source of the error related to `pymupdf` is not clear cut yet. Sometimes I get that same error also with more recent versions of that library. One thing that seems to help is to install `pymupdf `separately from `pdf2doi`

**Comment by gzurowski** [comment]
> @gzurowski I just released version 1.7rc1 with this change. Can you test it on your end? Probably better test it in a dedicated empty environment. I did some test, and the source of the error related to `pymupdf` is not clear cut yet. Sometimes I get that same error also with more recent versions of that library. One thing that seems to help is to install `pymupdf `separately from `pdf2doi`

Thank you so much, this works for me without issues. Does it make sense to loosen the restriction?
```
pymupdf>=1.24.9
```
This might also address issues like the following: https://github.com/MicheleCotrufo/pdf2doi/issues/37

**Comment by MicheleCotrufo** [comment]
Yeah, good idea. I will set it to `pymupdf>=1.21.0`

**Comment by gzurowski** [comment]
> Yeah, good idea. I will set it to `pymupdf>=1.21.0`

Thank you for making these changes. Will you release a `1.7.0` with this?
