### ISSUE TITLE
Request to dx.doi.org doesn't finish

### ISSUE THREAD

**Issue by c-langlet** [MicheleCotrufo/pdf2doi#35]
There seems to be a bug when querying the dx.doi.org server to ensure DOI existence throught the requests API.

I managed to solve the bug by changing url definition in pdf2doi.finders.validate_doi_web from (line 48):
`url = "http://dx.doi.org/" + doi
`
to 
`url = "https://dx.doi.org/" + doi
`

My configuration:
```
python 3.10
pdf2doi 1.6
requests 2.25.1
```

Thanks for the useful module !

**Comment by c-langlet** [comment]
I don't get any, the request never ends

**Comment by MicheleCotrufo** [comment]
Thanks, I'll change the url as you suggested in the next version

**Comment by MicheleCotrufo** [comment]
I implemented this change in version 1.7 (just published), please re-open the issue if the problem persists.
