### ISSUE TITLE
Cannot install due to requirement : pymupdf==1.24.9

### ISSUE THREAD

**Issue by Synapse203** [MicheleCotrufo/pdf2doi#37]
Hi, I'm coming from pdf-renamer

I know it's the same as other issues previously opened but it was about "pymupdf==1.21.0", the requirements.txt was updated with the 1.24.9 version but the problem is back..

Thanks a lot for your work

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by ShekharNarayanan** [comment]
Same issue for me! 
ERROR: Failed to build installable wheels for some pyproject.toml based projects (pymupdf)

**Comment by gzurowski** [comment]
This should be fixed with https://github.com/MicheleCotrufo/pdf2doi/issues/32#issuecomment-2466909608.

**Comment by MicheleCotrufo** [comment]
This should be fixed with version 1.7 (just published), please re-open the issue if the problem persists.
