### ISSUE TITLE
Export/Save to CSV? Import From CSV?

### ISSUE THREAD

**Issue by Pathos315** [MicheleCotrufo/pdf2doi#7]
May be a bit involved, but my hunch is that a factory pattern could be used to allow for either importing info from a directory OR a row in a CSV.

Similarly, it'd be great if this exported to a CSV/not just the console. This I've done in my own program. As I've mentioned to you already, however, it's had some problems (namely Pandas isn't happy with some of the keys I've given it).

**Comment by MicheleCotrufo** [comment]
Do you mean exporting all found DOIs to a .CSV file?
It is already possible to export all results to a .txt file, with [tab] separations (type `pdf2doi --h` to see the command required).
It should be fairly easy to convert that txt file to CSV.

**Comment by Pathos315** [comment]
I had meant to reply to this sooner, my apologies:

I had meant exporting entries into a .csv file (one row per entry), rather than a text file. This is something that I did for _pdfcurate_ using pandas, which uses pdf2doi to get the lions share of citation data. It's a functionality that I get quite a bit of use from, as most of my own work related to academic papers is with databases.
