### ISSUE TITLE
Possible optimization for main.py

### ISSUE THREAD

**Issue by Pathos315** [MicheleCotrufo/pdf2doi#8]
Currently, lines 425 to 428 in main read:

```
    for result in results:
        if result['identifier']:
            print('{:<15s} {:<40s} {:<10s}\n'.format(result['identifier_type'], result['identifier'],result['path']) ) 

    return
```

I suspect this could be improved/updated with an f-string:

```
    for result in results:
        if result['identifier']:
            print(f'{result['identifier_type']}, {result['identifier'], {result['path']} \n')

    return
```

**Comment by MicheleCotrufo** [comment]
Thanks for this suggestion! The main reason why I use the `{:<15s} {:<40s} {:<10s} ` part is to make sure that the correct tabulation spaces are  kept, and to give an overall more "tabular" look to the output
